### ISSUE TITLE
Update Go version to 1.20

### ISSUE THREAD

**Issue by CryoByte33** [fyne-io/fyne-cross-images#16]
### Is your feature request related to a problem? Please describe:
I'm using features new in Go 1.20 for my project, and it fails to compile.
```
internal/ui_authentication.go:16:6: cmd.WaitDelay undefined (type *exec.Cmd has no field or method WaitDelay)
internal/ui_authentication.go:52:6: cmd.WaitDelay undefined (type *exec.Cmd has no field or method WaitDelay)
note: module requires Go 1.20
[✗] exit status 2
```

Upon investigation, I saw that the base image is still using Go `1.18.4` and Fyne `v2.2.3`.

As I develop on an M2 Macbook, fyne-cross is my simplest solution to build for Linux x64 systems consistently.

### Is it possible to construct a solution with the existing API?
N/A

### Describe the solution you'd like to see:
A simple update to the latest Go and Fyne versions would be more than enough.

**Comment by Jacalz** [comment]
I realised that this makes more sense in `fyne-cross-images` so I transferred it over to there.

**Comment by Jacalz** [comment]
As of #17 being merged, this is now resolved. I suspect we will have a new release out once more testing has been done.
