### ISSUE TITLE
Consider updating to stable Zig 0.11.0 release

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne-cross-images#21]
We should consider using the stable [Zig 0.11.0](https://ziglang.org/download/0.11.0/release-notes.html) release instead of the development version.

**Comment by Bluebugs** [comment]
Considering how tricky last update was, I think we should hold onto that one for the moment, except if it does solve a known bug. 

My personal idea to update zig, is to update the image just with zig as a change and check how that work out for all targets (amd64 and arm64).

**Comment by Jacalz** [comment]
Indeed, I know that it was tricky and that is why I said to consider the update :)
