### ISSUE TITLE
Building without fyne-cross

### ISSUE THREAD

**Issue by RotciViL** [fyne-io/fyne-cross-images#30]
Hello, i've be trying to use the darwin image(fyneio/fyne-cross-images:1.1.3-darwin) from this repo in my CI/CD pipeline to build my fyne app.

Locally, to get in the image, i do this command:

Note: I'm in my project directory.

`docker run -ti --rm -v .:/src -v .\SDKs\MacOSX11.3.sdk\:/sdk fyneio/fyne-cross-images:1.1.3-darwin /bin/bash`

in the image, i set these variables coming from the fyne-cross [repository](https://github.com/fyne-io/fyne-cross/blob/master/internal/command/darwin.go) (line 233):
`go env -w CC="zig cc -v -target x86_64-macos.10.12 -isysroot /sdk -iwithsysroot /usr/include -iframeworkwithsysroot /System/Library/Frameworks"`
`go env -w CXX="zig c++ -v -target x86_64-macos.10.12 -isysroot /sdk -iwithsysroot /usr/include -iframeworkwithsysroot /System/Library/Frameworks"`
`go env -w CGO_LDFLAGS="--sysroot /sdk -F/System/Library/Frameworks -L/usr/lib"`
`go env -w GOOS=darwin`

however, after trying:
`fyne package --appID myapp --os darwin`

I get this error:
[log.txt](https://github.com/fyne-io/fyne-cross-images/files/12749190/log.txt)

am i missing something ?

**Comment by Bluebugs** [comment]
I don't think we will want to support this use as this is likely going to significantly increase the _bugs reports_ that aren't. If you really do not want to use fyne-cross directly, the only things that is supposed to work is the exact command that are set here: `https://github.com/fyne-io/fyne-cross/blob/master/internal/command/darwin.go#L233` and around. Seems you are missing a few.
